categories:
  - id: sdk
    name: Psy-Q SDK
    paths:
      - slus_006.64/psyq
  - id: main
    name: Main Executable
    paths:
      - slus_006.64

expected_paths:
  asm: expected/asm
  src: expected/src

ignored_files:
  - main/header

output: ./objdiff.json