categories:
  - id: sdk
    name: Psy-Q SDK
    paths:
      - psyq
  - id: main
    name: Main Executable
    paths:
      - main

expected_paths:
  asm: expected/asm
  src: expected/src

ignored_files:
  - main/header

output: ./objdiff.json