name: Field Overlay
sha1: 7bdc0e2be7797ab821fb7d0ce10438a0e91f4c7b
options:
  basename: field.bin
  target_path: disc/FIELD.BIN
  base_path: ../
  platform: psx
  compiler: PSYQ

  asm_path: asm/field
  src_path: src/field
  build_path: build/

  ld_script_path: linker/field.ld

  find_file_boundaries: False
  gp_value: 0x80059170
  global_vram_start: 0x80010000

  o_as_suffix: False
  use_legacy_include_asm: False

  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel

  section_order: [".rodata", ".text", ".data", ".bss"]

  symbol_addrs_path:
    - config/symbol_addrs.field.txt
    - config/symbol_addrs.slus_006.64.txt
  reloc_addrs_path:
    - configs/reloc_addrs.field.txt

  undefined_funcs_auto_path: linker/undefined_funcs_auto.field.txt
  undefined_syms_auto_path: linker/undefined_syms_auto.field.txt

  extensions_path: tools/splat_ext

  subalign: 4

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - name: field
    type: code
    start: 0x0
    vram: 0x8006faf0
    align: 4
    subalign: 4
    subsegments:
      - [0x0, rodata]
      - [0x2FC, asm]
      - [0x23F8, c, main/init]
      - [0x2650, asm]
      - [0x7AD0, c, main/main]
      - [0x906C, asm]
      - [0x32384, c, scripts/virtual_machine]
      - [0x3D334, asm]
      - [0x3DF78, data]
  - [0x3FAFC, databin]
  - [0x3FAFE]