name: Movie Overlay
sha1: e7ff2568b918b75e290050597c86584f3499ebdf
options:
  basename: movie.bin
  target_path: disc/MOVIE.BIN
  base_path: ../
  platform: psx
  compiler: PSYQ

  asm_path: asm/movie
  src_path: src/movie
  build_path: build/

  ld_script_path: linker/movie.ld

  find_file_boundaries: False
  gp_value: 0x80059170
  global_vram_start: 0x80010000

  o_as_suffix: False
  use_legacy_include_asm: False

  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel

  section_order: [".rodata", ".text", ".data", ".bss"]

  symbol_addrs_path:
    - config/symbol_addrs.movie.txt
    - config/symbol_addrs.slus_006.64.txt
  reloc_addrs_path:
    - configs/reloc_addrs.movie.txt

  undefined_funcs_auto_path: linker/undefined_funcs_auto.movie.txt
  undefined_syms_auto_path: linker/undefined_syms_auto.movie.txt

  extensions_path: tools/splat_ext

  subalign: 4

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - name: movie
    type: code
    start: 0x0
    vram: 0x8006faf0
    align: 4
    subalign: 4
    subsegments:
      - [0x0, rodata]
      - [0x7DC, asm]
      - [0x7354, data]
  - [0x7450, databin]
  - [0x7453]