name: Main Game Logic Overlay
sha1: 7bdc0e2be7797ab821fb7d0ce10438a0e91f4c7b
options:
  basename: overlay1.bin
  target_path: disc/OVERLAY_0x1.BIN
  base_path: ../
  platform: psx
  compiler: PSYQ

  asm_path: asm/overlay1
  src_path: src/overlay1
  build_path: build/

  ld_script_path: linker/overlay1.ld

  find_file_boundaries: False
  gp_value: 0x80059170
  global_vram_start: 0x80010000

  o_as_suffix: False
  use_legacy_include_asm: False

  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel

  section_order: [".rodata", ".text", ".data", ".bss"]

  symbol_addrs_path:
    - config/symbol_addrs.overlay1.txt
    - config/symbol_addrs.slus_006.64.txt
  reloc_addrs_path:
    - configs/reloc_addrs.overlay1.txt

  undefined_funcs_auto_path: linker/undefined_funcs_auto.overlay1.txt
  undefined_syms_auto_path: linker/undefined_syms_auto.overlay1.txt

  extensions_path: tools/splat_ext

  subalign: 4

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - name: overlay1
    type: code
    start: 0x0
    vram: 0x006faf0
    align: 4
    subalign: 4
    subsegments:
      - [0x0, rodata]
      - [0x2FC, asm]
      - [0x3DF78, data]
  - [0x3FAFC, databin]
  - [0x3FAFE]