name: Xenogears (USA)
sha1: 560bbdbeb9264c935294ecad5a3d4ab230a006a9
options:
  basename: slus_006.64
  target_path: disc/SLUS_006.64
  elf_path: build/slus_006.64.elf
  base_path: ../
  platform: psx
  compiler: PSYQ

  asm_path: asm/slus_006.64
  src_path: src/slus_006.64
  build_path: build
  # create_asm_dependencies: True

  ld_script_path: linker/slus_006.64.ld
  ld_dependencies: True

  find_file_boundaries: False
  gp_value: 0x80059170
  global_vram_start: 0x80010000

  o_as_suffix: False
  use_legacy_include_asm: False

  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel

  section_order: [".rodata", ".text", ".sdata", ".data", ".sbss", ".bss"]
  # auto_link_sections: [".data", ".rodata", ".bss"]

  symbol_addrs_path: 
    - config/symbol_addrs.slus_006.64.txt
  reloc_addrs_path: 
    - config/reloc_addrs.txt

  undefined_funcs_auto_path: linker/undefined_funcs_auto.slus_006.64.txt
  undefined_syms_auto_path: linker/undefined_syms_auto.slus_006.64.txt

  extensions_path: tools/splat_ext

  subalign: 4

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2

  ld_bss_is_noload: True
segments:
  - name: header
    type: header
    start: 0x0

  - name: main
    type: code
    start: 0x800
    vram: 0x80010000
    bss_size: 0x544
    bss_contains_common: True
    align: 4
    subsegments:
      - [0x800, rodata]
      - [0x90F4, .rodata, system/archive]
      - [0x9144, rodata]
      - [0x9258, .rodata, system/memory]
      - [0x927C, rodata]
      - [0x9CE0, asm] 
      - [0x9D60, hasm]
      - [0x9D78, c, main/main] # main
      - [0xA164, asm]
      - [0xA16C, c, main/main_loop]
      - [0xA9E4, asm]
      - [0x18A30, c, system/archive]
      - [0x1B424, asm]
      - [0x22094, c, system/memory]
      - [0x235CC, c, system/heap_debug]
      - [0x23688, hasm, util/lzss]
      - [0x23754, asm]
      - [0x25E9C, c, system/controller]
      - [0x26644, asm]
      - [0x31508, c, psyq/libcd]
      - [0x3358C, asm]
      #- [0x3C720, c, system/interrupts] # InitVsyncInterrupts
      #- [0x3C778, c, system/interrupts] # VsyncInterruptHandler
      - [0x3C7F0, c, psyq/interrupts]
      - [0x3C848, asm]
      - [0x3F290, sdata]
      - [0x49A48, .sdata, system/memory]
      - [0x49AB8, .sdata, system/heap_debug]
      - [0x49ABC, data]
      - { vram: 0x800592C0, type: sbss }
      - { vram: 0x80059318, type: scommon, name: system/memory }
      - { vram: 0x80059348, type: scommon, name: system/heap_debug }
      - { vram: 0x80059350, type: bss }
  - [0x49AC0, rodatabin]
  - [0x4A000]
