
name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      fail-fast: true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -U -r requirements.txt
          sudo apt-get update
          sudo apt-get install make binutils-mips-linux-gnu cpp-mips-linux-gnu

      - name: Setup build environment
        run: |
          curl -o disc/SLUS_006.64 "${{ secrets.FILE_URL }}"

      #- name: Build and create progress report
      #  run: make report

      - name: Build
        run: |
          make generate
          make build

      - name: Check match
        run: make check

      #- name: Upload progress report
      #  uses: actions/upload-artifact@v4
      #  with:
      #      name: slus_006.64_report
      #      path: ./build/progress.json
